name: Build and upload Docker image

on:
  push:
    branches:
    - master
    - qt515

jobs:
  build_qt5_armhf_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: antoniobl/qt515musescore
        build_args: ARCH=armhf
        tags: armhf

  build_qt5_arm64_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Retrieve disk space
      run: |
        sudo docker system prune -a -f
        sudo rm -rf /usr/local/lib/android
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: antoniobl/qt515musescore
        build_args: ARCH=arm64
        tags: arm64

